name: Validate asset images

# **What it does**: Run ./script/validate-asset-images.js on all images in assets/
# **Why we have it**: To protect from innocent and potentially malicious bad image assets
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**'

permissions:
  contents: read

jobs:
  validate-asset-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: ./.github/actions/node-npm-setup

      - name: Validate all asset images
        run: ./script/validate-asset-images.js
